### ISSUE TITLE
function shout(string)

### ISSUE THREAD

**Issue by Tiffanyman19** [learn-co-curriculum/phase-0-pac-3-intro-to-functions-lab#34]
### Canvas Link

https://github.com/learn-co-curriculum/phase-0-pac-3-intro-to-functions-lab

### Concern

I followed the instructions to declare the function in index.js.  I even put the "return string.toUpperCase(); " and I still receive the same error that shout is not defined. I noticed that the code is slightly different from the instructions and the code I receive. I went over the instructions for this part over and over. I still receive the same error that shout was not define. I followed the instructions correctly.

![Screenshot 2023-10-30 114626](https://github.com/learn-co-curriculum/phase-0-pac-3-intro-to-functions-lab/assets/127052016/e5f72a0a-cfe2-406f-8331-b3d1370976db)

![Screenshot 2023-10-30 114749](https://github.com/learn-co-curriculum/phase-0-pac-3-intro-to-functions-lab/assets/127052016/be1ef6bc-9e09-4b09-9e1a-2d348e6a398b)

![Screenshot 2023-10-30 114125](https://github.com/learn-co-curriculum/phase-0-pac-3-intro-to-functions-lab/assets/127052016/cdf9996a-3306-4543-be9e-94e9ca42ea90)

![Screenshot 2023-10-30 113908](https://github.com/learn-co-curriculum/phase-0-pac-3-intro-to-functions-lab/assets/127052016/8445de82-80c8-4af3-b9c2-60a8ee116c0e)

**Comment by lizbur10** [comment]
Hi @Tiffanyman19 ! From the screenshot you posted it looks like you may just need to save the file - the white dot on the `index.js` tab indicates that there are unsaved changes. 

If saving the file doesn't fix the problem, you can use [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) to get live help.

Good luck!

**Comment by Tiffanyman19** [comment]
Hi @lizbur10 . I did what you said and I saved the file. I still receive the same issue.

**Comment by Tiffanyman19** [comment]
I have tried attempting to access to Ask Ada, and I am having trouble with it. This is regarding to prep work for Software Engineering.

**Comment by lizbur10** [comment]
Hi @Tiffanyman19  - so sorry you're still having problems! 

There should be a chat button in the lower right corner of the Canvas page. If you click that, you should then be able to click a button labeled "Talk to a Tech Coach". Tech Coaches are available from 12pm to midnight Eastern time.

If you don't see the button, or if clicking it doesn't work, you'll need to reach out to the Flatiron Operations team at operations@flatironschool.com. They will be able to figure out what the problem is and help you access Pair with a Coach.
