### ISSUE TITLE
function shout(string) #34

### ISSUE THREAD

**Issue by Tiffanyman19** [learn-co-curriculum/phase-0-pac-3-intro-to-functions-lab#35]
### Canvas Link

https://github.com/learn-co-curriculum/phase-0-pac-3-intro-to-functions-lab

### Concern

Same issue from #34 . The issue wasn't resolved and I received that the issue was completed. The issue has not been resolved yet. I have saved multiple times and the issue has not been resolved. I received the link, which says it was moved. I also tried accessing to Ask Ada, and I can not access it.

The person who told me to save it and then immediately closed the case, before I can even reply back. I looked at other issues, and I noticed that this is not the first time the issue with Introduction to Functions Lab has occured.

Please advise.

**Comment by lizbur10** [comment]
Hi again @Tiffanyman19 ! I hope you were able to get this resolved. Since this is not something our team can help you with, I'm going to go ahead and close this issue. If you are still not able to access Pair with a Coach, please reach out to to the Flatiron Operations team at [operations@flatironschool.com](mailto:operations@flatironschool.com).

Good luck!
